### ISSUE TITLE
Can't start service

### ISSUE THREAD

**Issue by kaihansen79** [simone-sanfratello/node-service-systemd#1]
Hello,

When I run 'sudo node-systemd add service-template.json', I get:
 
WARNING: wrap.bin not found
parsing ...
writing script start/stop files, logrotate.d ...
> chmod a+x /usr/local/bin/systemd-my-node-service*
writing systemd file ...
/etc/systemd/system/my-node-service.service
installing ...
> systemctl enable my-node-service.service;systemctl daemon-reload
done

And when I try to run 'sudo service <app-name.js> start', the service fails. Checking 'journalctl' shows:

Starting <app description> service...
/usr/local/bin/systemd-<app-name>-start: line 2: /usr/bin/forever: No such file or directory
PID file /var/run/<app-name>.pid not readable (yet?) after start.
Failed to start <app description> service
Unit <app-name>.service entered failed state.
<app-name>.service failed.

I've found some sources that suggest things like symlinks, but none of that seems to fix the issue. Any idea what's going on here?

Running this on Ubuntu 15.04.

Thanks,
Kai

**Comment by simone-sanfratello** [comment]
Hi Kai, I think you missed some steps

Did you installed forever? Can you attach your service-template.json file?

Thanks
