### ISSUE TITLE
systemd and forever are doing the same thing ?

### ISSUE THREAD

**Issue by kapouer** [simone-sanfratello/node-service-systemd#3]
Forever is meant to keep a node app running.
But you don't need that kind of feature because systemd already provides it.
Or am i missing something ?

**Comment by simone-sanfratello** [comment]
You are right, but using forever let (me) use forever tools, like forever-monitor.
I would like to add also support to pm2 and without wrapper, as you said.

**Comment by simone-sanfratello** [comment]
I added the wrap option "node" in the last version; I'm not satisfied due of missing log management feature. I don't know what the "best practice" is, I mean, wirte into the app the log management ignoring stdout and stderr? Any other option? Any suggestion are welcome.
